.TH "reproductor Directory Reference" 3 "Fri Oct 30 2020" "Version 1.0" "Odyssey Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reproductor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBreproductor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBreproductor\&.h\fP"
.br
.in -1c
