.TH "reproductor/main.cpp" 3 "Fri Oct 30 2020" "Version 1.0" "Odyssey Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reproductor/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'reproductor\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Odyssey Radio from the source code\&.
