.TH "Reproductor" 3 "Fri Oct 30 2020" "Version 1.0" "Odyssey Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reproductor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reproductor\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReproductor\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~Reproductor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Reproductor::Reproductor (QWidget * parent = \fCnullptr\fP)"

.SS "Reproductor::~Reproductor ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Odyssey Radio from the source code\&.
