.TH "reproductor/reproductor.cpp" 3 "Fri Oct 30 2020" "Version 1.0" "Odyssey Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reproductor/reproductor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'reproductor\&.h'\fP
.br
\fC#include 'ui_reproductor\&.h'\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMediaMetaData>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <qmediaservice\&.h>\fP
.br
\fC#include <qmediaplaylist\&.h>\fP
.br
\fC#include <qvideoprobe\&.h>\fP
.br
\fC#include <QDebug>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Odyssey Radio from the source code\&.
